# Generated by Django 5.1.2 on 2024-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word_created_at_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='Antonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Audio_in_English',
            field=models.FileField(blank=True, null=True, upload_to='audio/english/'),
        ),
        migrations.AddField(
            model_name='word',
            name='Audio_in_Yoruba',
            field=models.FileField(blank=True, null=True, upload_to='audio/yoruba/'),
        ),
        migrations.AddField(
            model_name='word',
            name='Common_Phrases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Cultural_Note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Dialect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Difficulty_Level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='English_Word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Etymology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Examples_in_English',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Examples_in_Yoruba',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Grammar_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='Interactive_Elements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Plural_Form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Proverbs_or_Idioms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Related_Words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Root_Word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Tonal_Marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Usage_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Word_Frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='Yoruba_Word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
